name: shell options demo

on: push
jobs:
  python:
    runs-on: ubuntu-22.04
    steps:
      - name: Run python
        shell: python
        run: |
          import sys
          print(sys.version)
  bash:
    runs-on: ubuntu-22.04
    steps:
      - name: Run Bash
        run: |
          false | echo 'error occurred'
          echo 'after error' # this command will be triggered
      - name: Run Bash with shell specification
        shell: bash
        run: |
          false | echo 'error occurred'
          echo 'after error' # this command will not be triggered
  docker-compose:
    timeout-minutes: 1
    runs-on: ubuntu-22.04
    steps:
      - name: docker-compose
        shell: "docker compose -f {0} up --build"
        run: |
          services:
            connect:
              image: ubuntu:latest
              restart: always
              entrypoint:
                - "bash"
                - "-c"
                - "echo 'conn' > /dev/tcp/db/3306"
            db:
              image: mysql:latest
              environment:
                MYSQL_ALLOW_EMPTY_PASSWORD: yes
              ports:
                - 3306:3306

