name: shell options demo

on: push
jobs:
  python:
    runs-on: ubuntu-22.04
    steps:
      - name: Run python
        shell: python
        run: |
          import sys
          print(sys.version)
  bash:
    runs-on: ubuntu-22.04
    steps:
      - name: Run Bash
        run: |
          false | echo 'error occurred'
          echo 'after error' # this command will be triggered
      - name: Run Bash with shell specification
        shell: bash
        run: |
          false | echo 'error occurred'
          echo 'after error' # this command will not be triggered
  go-as-shell:
    runs-on: ubuntu-22.04
    steps:
      - name: prepare go
        run: go mod init test
      - name: run with go
        shell: "go run {0}"
        run: |
          package main

          import (
                  "log"
                  "os"
          )

          func main() {
                  for _, v := range os.Environ() {
                          log.Println(v)
                  }
          }
